# Form implementation generated from reading ui file 'addpclayerdialog.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets


class Ui_AddPointCloudLayerDialog(object):
    def setupUi(self, AddPointCloudLayerDialog):
        AddPointCloudLayerDialog.setObjectName("AddPointCloudLayerDialog")
        AddPointCloudLayerDialog.resize(497, 102)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddPointCloudLayerDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=AddPointCloudLayerDialog)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit_Source = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_Source.setObjectName("lineEdit_Source")
        self.horizontalLayout_2.addWidget(self.lineEdit_Source)
        self.pushButton_Browse = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_Browse.setObjectName("pushButton_Browse")
        self.horizontalLayout_2.addWidget(self.pushButton_Browse)
        self.verticalLayout.addWidget(self.groupBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=AddPointCloudLayerDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Help|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(AddPointCloudLayerDialog)
        self.buttonBox.accepted.connect(AddPointCloudLayerDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(AddPointCloudLayerDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AddPointCloudLayerDialog)

    def retranslateUi(self, AddPointCloudLayerDialog):
        _translate = QtCore.QCoreApplication.translate
        AddPointCloudLayerDialog.setWindowTitle(_translate("AddPointCloudLayerDialog", "Add Point Cloud Layer"))
        self.groupBox.setTitle(_translate("AddPointCloudLayerDialog", "Source"))
        self.label.setText(_translate("AddPointCloudLayerDialog", "Potree supported file URL"))
        self.lineEdit_Source.setPlaceholderText(_translate("AddPointCloudLayerDialog", "http(s)://... or file://..."))
        self.pushButton_Browse.setText(_translate("AddPointCloudLayerDialog", "Browse..."))
