# Form implementation generated from reading ui file 'hflabeldialog.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets


class Ui_HFLabelDialog(object):
    def setupUi(self, HFLabelDialog):
        HFLabelDialog.setObjectName("HFLabelDialog")
        HFLabelDialog.resize(532, 282)
        self.verticalLayout = QtWidgets.QVBoxLayout(HFLabelDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=HFLabelDialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textEdit_Header = QtWidgets.QTextEdit(parent=HFLabelDialog)
        self.textEdit_Header.setObjectName("textEdit_Header")
        self.verticalLayout.addWidget(self.textEdit_Header)
        self.label_2 = QtWidgets.QLabel(parent=HFLabelDialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.textEdit_Footer = QtWidgets.QTextEdit(parent=HFLabelDialog)
        self.textEdit_Footer.setObjectName("textEdit_Footer")
        self.verticalLayout.addWidget(self.textEdit_Footer)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=HFLabelDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Apply|QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Help|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(HFLabelDialog)
        self.buttonBox.accepted.connect(HFLabelDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(HFLabelDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(HFLabelDialog)

    def retranslateUi(self, HFLabelDialog):
        _translate = QtCore.QCoreApplication.translate
        HFLabelDialog.setWindowTitle(_translate("HFLabelDialog", "Header Label and Footer Label"))
        self.label.setText(_translate("HFLabelDialog", "Header Label"))
        self.textEdit_Header.setPlaceholderText(_translate("HFLabelDialog", "Enter the text you want to display at the top of the page. It may contain valid HTML tags."))
        self.label_2.setText(_translate("HFLabelDialog", "Footer Label"))
        self.textEdit_Footer.setPlaceholderText(_translate("HFLabelDialog", "Enter the text you want to display at the bottom of the page. It may contain valid HTML tags."))
