# Form implementation generated from reading ui file 'northarrowdialog.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets


class Ui_NorthArrowDialog(object):
    def setupUi(self, NorthArrowDialog):
        NorthArrowDialog.setObjectName("NorthArrowDialog")
        NorthArrowDialog.resize(281, 101)
        self.verticalLayout = QtWidgets.QVBoxLayout(NorthArrowDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=NorthArrowDialog)
        self.groupBox.setCheckable(True)
        self.groupBox.setChecked(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.colorButton = QgsColorButton(parent=self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorButton.sizePolicy().hasHeightForWidth())
        self.colorButton.setSizePolicy(sizePolicy)
        self.colorButton.setObjectName("colorButton")
        self.gridLayout.addWidget(self.colorButton, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=NorthArrowDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Apply|QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(NorthArrowDialog)
        self.buttonBox.accepted.connect(NorthArrowDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(NorthArrowDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(NorthArrowDialog)

    def retranslateUi(self, NorthArrowDialog):
        _translate = QtCore.QCoreApplication.translate
        NorthArrowDialog.setWindowTitle(_translate("NorthArrowDialog", "North Arrow"))
        self.groupBox.setTitle(_translate("NorthArrowDialog", "Enable North Arrow"))
        self.label.setText(_translate("NorthArrowDialog", "Color"))
from qgis.gui import QgsColorButton
