# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'animationpanel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AnimationPanel(object):
    def setupUi(self, AnimationPanel):
        AnimationPanel.setObjectName("AnimationPanel")
        AnimationPanel.resize(235, 30)
        self.verticalLayout = QtWidgets.QVBoxLayout(AnimationPanel)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.toolButtonRemove = QtWidgets.QToolButton(AnimationPanel)
        self.toolButtonRemove.setObjectName("toolButtonRemove")
        self.gridLayout_2.addWidget(self.toolButtonRemove, 0, 2, 1, 1)
        self.toolButtonPlay = QtWidgets.QToolButton(AnimationPanel)
        self.toolButtonPlay.setCheckable(True)
        self.toolButtonPlay.setObjectName("toolButtonPlay")
        self.gridLayout_2.addWidget(self.toolButtonPlay, 0, 5, 1, 1)
        self.toolButtonAdd = QtWidgets.QToolButton(AnimationPanel)
        self.toolButtonAdd.setObjectName("toolButtonAdd")
        self.gridLayout_2.addWidget(self.toolButtonAdd, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 3, 1, 1)
        self.toolButtonEdit = QtWidgets.QToolButton(AnimationPanel)
        self.toolButtonEdit.setObjectName("toolButtonEdit")
        self.gridLayout_2.addWidget(self.toolButtonEdit, 0, 1, 1, 1)
        self.checkBoxLoop = QtWidgets.QCheckBox(AnimationPanel)
        self.checkBoxLoop.setObjectName("checkBoxLoop")
        self.gridLayout_2.addWidget(self.checkBoxLoop, 0, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)

        self.retranslateUi(AnimationPanel)
        QtCore.QMetaObject.connectSlotsByName(AnimationPanel)

    def retranslateUi(self, AnimationPanel):
        _translate = QtCore.QCoreApplication.translate
        self.toolButtonRemove.setToolTip(_translate("AnimationPanel", "Remove selected keyframe item(s) or group."))
        self.toolButtonRemove.setText(_translate("AnimationPanel", "-"))
        self.toolButtonPlay.setToolTip(_translate("AnimationPanel", "Perform the checked animations in parallel."))
        self.toolButtonPlay.setText(_translate("AnimationPanel", "Play"))
        self.toolButtonAdd.setToolTip(_translate("AnimationPanel", "Add a keyframe group and/or a keyframe item."))
        self.toolButtonAdd.setText(_translate("AnimationPanel", "+"))
        self.toolButtonEdit.setToolTip(_translate("AnimationPanel", "Open keyframe dialog for current item."))
        self.toolButtonEdit.setText(_translate("AnimationPanel", "Edit"))
        self.checkBoxLoop.setToolTip(_translate("AnimationPanel", "Repeat the entire animation."))
        self.checkBoxLoop.setText(_translate("AnimationPanel", "Loop"))
