# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Documents\minorua\QGIS\plugins\Qgis2threejs\ui\exporttowebdialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExportToWebDialog(object):
    def setupUi(self, ExportToWebDialog):
        ExportToWebDialog.setObjectName("ExportToWebDialog")
        ExportToWebDialog.resize(599, 391)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(ExportToWebDialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(ExportToWebDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tabSettings = QtWidgets.QWidget()
        self.tabSettings.setObjectName("tabSettings")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabSettings)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_General = QtWidgets.QGroupBox(self.tabSettings)
        self.groupBox_General.setObjectName("groupBox_General")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_General)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox_General)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_OutputDir = QtWidgets.QLineEdit(self.groupBox_General)
        self.lineEdit_OutputDir.setObjectName("lineEdit_OutputDir")
        self.horizontalLayout.addWidget(self.lineEdit_OutputDir)
        self.pushButton_Browse = QtWidgets.QPushButton(self.groupBox_General)
        self.pushButton_Browse.setObjectName("pushButton_Browse")
        self.horizontalLayout.addWidget(self.pushButton_Browse)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_3 = QtWidgets.QLabel(self.groupBox_General)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_Filename = QtWidgets.QLineEdit(self.groupBox_General)
        self.lineEdit_Filename.setObjectName("lineEdit_Filename")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Filename)
        self.label_4 = QtWidgets.QLabel(self.groupBox_General)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_Title = QtWidgets.QLineEdit(self.groupBox_General)
        self.lineEdit_Title.setObjectName("lineEdit_Title")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Title)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.checkBox_PreserveViewpoint = QtWidgets.QCheckBox(self.groupBox_General)
        self.checkBox_PreserveViewpoint.setObjectName("checkBox_PreserveViewpoint")
        self.verticalLayout_2.addWidget(self.checkBox_PreserveViewpoint)
        self.checkBox_LocalMode = QtWidgets.QCheckBox(self.groupBox_General)
        self.checkBox_LocalMode.setObjectName("checkBox_LocalMode")
        self.verticalLayout_2.addWidget(self.checkBox_LocalMode)
        self.verticalLayout_3.addWidget(self.groupBox_General)
        self.groupBox_Template = QtWidgets.QGroupBox(self.tabSettings)
        self.groupBox_Template.setObjectName("groupBox_Template")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_Template)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox_Template)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setObjectName("label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.comboBox_Template = QtWidgets.QComboBox(self.groupBox_Template)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Template.sizePolicy().hasHeightForWidth())
        self.comboBox_Template.setSizePolicy(sizePolicy)
        self.comboBox_Template.setObjectName("comboBox_Template")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_Template)
        self.label_MND = QtWidgets.QLabel(self.groupBox_Template)
        self.label_MND.setWordWrap(True)
        self.label_MND.setObjectName("label_MND")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_MND)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_MND = QtWidgets.QLineEdit(self.groupBox_Template)
        self.lineEdit_MND.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_MND.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.lineEdit_MND.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_MND.setObjectName("lineEdit_MND")
        self.gridLayout.addWidget(self.lineEdit_MND, 0, 0, 1, 1)
        self.label_MND2 = QtWidgets.QLabel(self.groupBox_Template)
        self.label_MND2.setObjectName("label_MND2")
        self.gridLayout.addWidget(self.label_MND2, 0, 1, 1, 1)
        self.formLayout_3.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.gridLayout)
        self.verticalLayout_3.addWidget(self.groupBox_Template)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.tabWidget.addTab(self.tabSettings, "")
        self.tabLog = QtWidgets.QWidget()
        self.tabLog.setObjectName("tabLog")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabLog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.tabLog)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.tabWidget.addTab(self.tabLog, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.progressBar = QtWidgets.QProgressBar(ExportToWebDialog)
        self.progressBar.setEnabled(False)
        self.progressBar.setMinimumSize(QtCore.QSize(400, 0))
        self.progressBar.setFormat("%p%")
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_2.addWidget(self.progressBar)
        self.pushButton_Cancel = QtWidgets.QPushButton(ExportToWebDialog)
        self.pushButton_Cancel.setEnabled(False)
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.horizontalLayout_2.addWidget(self.pushButton_Cancel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pushButton_Export = QtWidgets.QPushButton(ExportToWebDialog)
        self.pushButton_Export.setDefault(True)
        self.pushButton_Export.setObjectName("pushButton_Export")
        self.horizontalLayout_3.addWidget(self.pushButton_Export)
        self.pushButton_Close = QtWidgets.QPushButton(ExportToWebDialog)
        self.pushButton_Close.setObjectName("pushButton_Close")
        self.horizontalLayout_3.addWidget(self.pushButton_Close)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)

        self.retranslateUi(ExportToWebDialog)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton_Export.clicked.connect(ExportToWebDialog.accept)
        self.pushButton_Close.clicked.connect(ExportToWebDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ExportToWebDialog)
        ExportToWebDialog.setTabOrder(self.tabWidget, self.lineEdit_OutputDir)
        ExportToWebDialog.setTabOrder(self.lineEdit_OutputDir, self.pushButton_Browse)
        ExportToWebDialog.setTabOrder(self.pushButton_Browse, self.lineEdit_Filename)
        ExportToWebDialog.setTabOrder(self.lineEdit_Filename, self.lineEdit_Title)
        ExportToWebDialog.setTabOrder(self.lineEdit_Title, self.checkBox_PreserveViewpoint)
        ExportToWebDialog.setTabOrder(self.checkBox_PreserveViewpoint, self.checkBox_LocalMode)
        ExportToWebDialog.setTabOrder(self.checkBox_LocalMode, self.comboBox_Template)
        ExportToWebDialog.setTabOrder(self.comboBox_Template, self.lineEdit_MND)
        ExportToWebDialog.setTabOrder(self.lineEdit_MND, self.textBrowser)
        ExportToWebDialog.setTabOrder(self.textBrowser, self.pushButton_Cancel)
        ExportToWebDialog.setTabOrder(self.pushButton_Cancel, self.pushButton_Export)
        ExportToWebDialog.setTabOrder(self.pushButton_Export, self.pushButton_Close)

    def retranslateUi(self, ExportToWebDialog):
        _translate = QtCore.QCoreApplication.translate
        ExportToWebDialog.setWindowTitle(_translate("ExportToWebDialog", "Export to Web"))
        self.groupBox_General.setTitle(_translate("ExportToWebDialog", "General"))
        self.label_2.setText(_translate("ExportToWebDialog", "Output Directory"))
        self.lineEdit_OutputDir.setToolTip(_translate("ExportToWebDialog", "Leave this empty to export files to temporary directory."))
        self.lineEdit_OutputDir.setPlaceholderText(_translate("ExportToWebDialog", "[Temporary directory]"))
        self.pushButton_Browse.setText(_translate("ExportToWebDialog", "Browse..."))
        self.label_3.setText(_translate("ExportToWebDialog", "HTML Filename"))
        self.label_4.setText(_translate("ExportToWebDialog", "Page Title"))
        self.checkBox_PreserveViewpoint.setText(_translate("ExportToWebDialog", "Preserve the Current Viewpoint"))
        self.checkBox_LocalMode.setText(_translate("ExportToWebDialog", "Enable the Viewer to Run Locally"))
        self.groupBox_Template.setTitle(_translate("ExportToWebDialog", "Template"))
        self.label.setText(_translate("ExportToWebDialog", "Template"))
        self.label_MND.setText(_translate("ExportToWebDialog", "Magnetic North Direction"))
        self.lineEdit_MND.setToolTip(_translate("ExportToWebDialog", "clockwise from the upper direction of the map, in degrees"))
        self.lineEdit_MND.setText(_translate("ExportToWebDialog", "0"))
        self.label_MND2.setText(_translate("ExportToWebDialog", "degrees"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSettings), _translate("ExportToWebDialog", "Settings"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLog), _translate("ExportToWebDialog", "Log"))
        self.pushButton_Cancel.setText(_translate("ExportToWebDialog", "Cancel"))
        self.pushButton_Export.setText(_translate("ExportToWebDialog", "Export"))
        self.pushButton_Close.setText(_translate("ExportToWebDialog", "Close"))
