# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Documents\minorua\QGIS\plugins\Qgis2threejs\ui\keyframedialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KeyframeDialog(object):
    def setupUi(self, KeyframeDialog):
        KeyframeDialog.setObjectName("KeyframeDialog")
        KeyframeDialog.resize(400, 371)
        self.verticalLayout = QtWidgets.QVBoxLayout(KeyframeDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.labelName = QtWidgets.QLabel(KeyframeDialog)
        self.labelName.setObjectName("labelName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelName)
        self.lineEditName = QtWidgets.QLineEdit(KeyframeDialog)
        self.lineEditName.setObjectName("lineEditName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditName)
        self.label_2 = QtWidgets.QLabel(KeyframeDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEditDuration = QtWidgets.QLineEdit(KeyframeDialog)
        self.lineEditDuration.setObjectName("lineEditDuration")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditDuration)
        self.label_3 = QtWidgets.QLabel(KeyframeDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEditDelay = QtWidgets.QLineEdit(KeyframeDialog)
        self.lineEditDelay.setObjectName("lineEditDelay")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEditDelay)
        self.label_4 = QtWidgets.QLabel(KeyframeDialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.labelTime = QtWidgets.QLabel(KeyframeDialog)
        self.labelTime.setFrameShape(QtWidgets.QFrame.Box)
        self.labelTime.setText("")
        self.labelTime.setObjectName("labelTime")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.labelTime)
        self.label_6 = QtWidgets.QLabel(KeyframeDialog)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.comboBoxEasing = QtWidgets.QComboBox(KeyframeDialog)
        self.comboBoxEasing.setObjectName("comboBoxEasing")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comboBoxEasing)
        self.labelOpacity = QtWidgets.QLabel(KeyframeDialog)
        self.labelOpacity.setObjectName("labelOpacity")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelOpacity)
        self.doubleSpinBoxOpacity = QtWidgets.QDoubleSpinBox(KeyframeDialog)
        self.doubleSpinBoxOpacity.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.doubleSpinBoxOpacity.setDecimals(1)
        self.doubleSpinBoxOpacity.setMaximum(1.0)
        self.doubleSpinBoxOpacity.setSingleStep(0.1)
        self.doubleSpinBoxOpacity.setProperty("value", 1.0)
        self.doubleSpinBoxOpacity.setObjectName("doubleSpinBoxOpacity")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxOpacity)
        self.verticalLayout.addLayout(self.formLayout)
        self.labelNarration = QtWidgets.QLabel(KeyframeDialog)
        self.labelNarration.setObjectName("labelNarration")
        self.verticalLayout.addWidget(self.labelNarration)
        self.textEdit = QtWidgets.QTextEdit(KeyframeDialog)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.buttonBox = QtWidgets.QDialogButtonBox(KeyframeDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(KeyframeDialog)
        self.buttonBox.accepted.connect(KeyframeDialog.accept)
        self.buttonBox.rejected.connect(KeyframeDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(KeyframeDialog)
        KeyframeDialog.setTabOrder(self.lineEditName, self.doubleSpinBoxOpacity)
        KeyframeDialog.setTabOrder(self.doubleSpinBoxOpacity, self.lineEditDuration)
        KeyframeDialog.setTabOrder(self.lineEditDuration, self.lineEditDelay)
        KeyframeDialog.setTabOrder(self.lineEditDelay, self.comboBoxEasing)
        KeyframeDialog.setTabOrder(self.comboBoxEasing, self.textEdit)

    def retranslateUi(self, KeyframeDialog):
        _translate = QtCore.QCoreApplication.translate
        KeyframeDialog.setWindowTitle(_translate("KeyframeDialog", "Keyframe"))
        self.labelName.setText(_translate("KeyframeDialog", "Name"))
        self.label_2.setText(_translate("KeyframeDialog", "Transition duration (msec)"))
        self.label_3.setText(_translate("KeyframeDialog", "Delay (msec)"))
        self.label_4.setText(_translate("KeyframeDialog", "Absolute time (msec)"))
        self.label_6.setText(_translate("KeyframeDialog", "Easing function"))
        self.labelOpacity.setText(_translate("KeyframeDialog", "Opacity"))
        self.labelNarration.setText(_translate("KeyframeDialog", "Narrative content"))
