# Form implementation generated from reading ui file 'layerselectdialog.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets


class Ui_LayerSelectDialog(object):
    def setupUi(self, LayerSelectDialog):
        LayerSelectDialog.setObjectName("LayerSelectDialog")
        LayerSelectDialog.resize(439, 425)
        self.verticalLayout = QtWidgets.QVBoxLayout(LayerSelectDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=LayerSelectDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_Tree = QtWidgets.QWidget()
        self.tab_Tree.setObjectName("tab_Tree")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_Tree)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.treeView = QgsLayerTreeView(parent=self.tab_Tree)
        self.treeView.setObjectName("treeView")
        self.gridLayout_2.addWidget(self.treeView, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_Tree, "")
        self.tab_Preview = QtWidgets.QWidget()
        self.tab_Preview.setObjectName("tab_Preview")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_Preview)
        self.gridLayout.setObjectName("gridLayout")
        self.canvas = QgsMapCanvas(parent=self.tab_Preview)
        self.canvas.setObjectName("canvas")
        self.gridLayout.addWidget(self.canvas, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_Preview, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=LayerSelectDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(LayerSelectDialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(LayerSelectDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(LayerSelectDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LayerSelectDialog)

    def retranslateUi(self, LayerSelectDialog):
        _translate = QtCore.QCoreApplication.translate
        LayerSelectDialog.setWindowTitle(_translate("LayerSelectDialog", "Select layer(s)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Tree), _translate("LayerSelectDialog", "Layers"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Preview), _translate("LayerSelectDialog", "Preview"))
from qgis.gui import QgsLayerTreeView, QgsMapCanvas
