# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Users\minorua\.qgis2\python\developing_plugins\Qgis2threejs\ui\demproperties.ui'
#
# Created: Mon Dec 15 15:47:22 2014
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DEMPropertiesWidget(object):
    def setupUi(self, DEMPropertiesWidget):
        DEMPropertiesWidget.setObjectName(_fromUtf8("DEMPropertiesWidget"))
        DEMPropertiesWidget.resize(437, 604)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DEMPropertiesWidget.sizePolicy().hasHeightForWidth())
        DEMPropertiesWidget.setSizePolicy(sizePolicy)
        self.gridLayout = QtGui.QGridLayout(DEMPropertiesWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.formLayout_DEMLayer = QtGui.QFormLayout()
        self.formLayout_DEMLayer.setObjectName(_fromUtf8("formLayout_DEMLayer"))
        self.label_DEMLayer = QtGui.QLabel(DEMPropertiesWidget)
        self.label_DEMLayer.setObjectName(_fromUtf8("label_DEMLayer"))
        self.formLayout_DEMLayer.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_DEMLayer)
        self.comboBox_DEMLayer = QtGui.QComboBox(DEMPropertiesWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_DEMLayer.sizePolicy().hasHeightForWidth())
        self.comboBox_DEMLayer.setSizePolicy(sizePolicy)
        self.comboBox_DEMLayer.setObjectName(_fromUtf8("comboBox_DEMLayer"))
        self.formLayout_DEMLayer.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBox_DEMLayer)
        self.verticalLayout_9.addLayout(self.formLayout_DEMLayer)
        self.groupBox_Resampling = QtGui.QGroupBox(DEMPropertiesWidget)
        self.groupBox_Resampling.setObjectName(_fromUtf8("groupBox_Resampling"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_Resampling)
        self.gridLayout_2.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_Simple = QtGui.QVBoxLayout()
        self.verticalLayout_Simple.setContentsMargins(10, -1, -1, -1)
        self.verticalLayout_Simple.setObjectName(_fromUtf8("verticalLayout_Simple"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.horizontalSlider_Resolution = QtGui.QSlider(self.groupBox_Resampling)
        self.horizontalSlider_Resolution.setEnabled(True)
        self.horizontalSlider_Resolution.setMinimum(1)
        self.horizontalSlider_Resolution.setMaximum(6)
        self.horizontalSlider_Resolution.setSingleStep(1)
        self.horizontalSlider_Resolution.setPageStep(1)
        self.horizontalSlider_Resolution.setProperty("value", 2)
        self.horizontalSlider_Resolution.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Resolution.setTickPosition(QtGui.QSlider.TicksBelow)
        self.horizontalSlider_Resolution.setTickInterval(1)
        self.horizontalSlider_Resolution.setObjectName(_fromUtf8("horizontalSlider_Resolution"))
        self.horizontalLayout.addWidget(self.horizontalSlider_Resolution)
        self.label_Resolution = QtGui.QLabel(self.groupBox_Resampling)
        self.label_Resolution.setMinimumSize(QtCore.QSize(80, 0))
        self.label_Resolution.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Resolution.setObjectName(_fromUtf8("label_Resolution"))
        self.horizontalLayout.addWidget(self.label_Resolution)
        self.verticalLayout_Simple.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_8 = QtGui.QLabel(self.groupBox_Resampling)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_4.addWidget(self.label_8)
        self.lineEdit_HRes = QtGui.QLineEdit(self.groupBox_Resampling)
        self.lineEdit_HRes.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_HRes.sizePolicy().hasHeightForWidth())
        self.lineEdit_HRes.setSizePolicy(sizePolicy)
        self.lineEdit_HRes.setReadOnly(True)
        self.lineEdit_HRes.setObjectName(_fromUtf8("lineEdit_HRes"))
        self.horizontalLayout_4.addWidget(self.lineEdit_HRes)
        self.label_9 = QtGui.QLabel(self.groupBox_Resampling)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_4.addWidget(self.label_9)
        self.lineEdit_VRes = QtGui.QLineEdit(self.groupBox_Resampling)
        self.lineEdit_VRes.setEnabled(True)
        self.lineEdit_VRes.setReadOnly(True)
        self.lineEdit_VRes.setObjectName(_fromUtf8("lineEdit_VRes"))
        self.horizontalLayout_4.addWidget(self.lineEdit_VRes)
        self.verticalLayout_Simple.addLayout(self.horizontalLayout_4)
        self.formLayout_Surroundings = QtGui.QFormLayout()
        self.formLayout_Surroundings.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.formLayout_Surroundings.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_Surroundings.setObjectName(_fromUtf8("formLayout_Surroundings"))
        self.checkBox_Surroundings = QtGui.QCheckBox(self.groupBox_Resampling)
        self.checkBox_Surroundings.setObjectName(_fromUtf8("checkBox_Surroundings"))
        self.formLayout_Surroundings.setWidget(1, QtGui.QFormLayout.LabelRole, self.checkBox_Surroundings)
        self.horizontalLayout_Surroundings = QtGui.QHBoxLayout()
        self.horizontalLayout_Surroundings.setObjectName(_fromUtf8("horizontalLayout_Surroundings"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_Surroundings.addItem(spacerItem)
        self.label_2 = QtGui.QLabel(self.groupBox_Resampling)
        self.label_2.setEnabled(False)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_Surroundings.addWidget(self.label_2)
        self.spinBox_Size = QtGui.QSpinBox(self.groupBox_Resampling)
        self.spinBox_Size.setEnabled(False)
        self.spinBox_Size.setMinimumSize(QtCore.QSize(70, 0))
        self.spinBox_Size.setMinimum(3)
        self.spinBox_Size.setMaximum(9)
        self.spinBox_Size.setSingleStep(2)
        self.spinBox_Size.setProperty("value", 5)
        self.spinBox_Size.setObjectName(_fromUtf8("spinBox_Size"))
        self.horizontalLayout_Surroundings.addWidget(self.spinBox_Size)
        self.label_3 = QtGui.QLabel(self.groupBox_Resampling)
        self.label_3.setEnabled(False)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_Surroundings.addWidget(self.label_3)
        self.spinBox_Roughening = QtGui.QSpinBox(self.groupBox_Resampling)
        self.spinBox_Roughening.setEnabled(False)
        self.spinBox_Roughening.setMinimumSize(QtCore.QSize(70, 0))
        self.spinBox_Roughening.setMinimum(2)
        self.spinBox_Roughening.setMaximum(64)
        self.spinBox_Roughening.setSingleStep(4)
        self.spinBox_Roughening.setProperty("value", 4)
        self.spinBox_Roughening.setObjectName(_fromUtf8("spinBox_Roughening"))
        self.horizontalLayout_Surroundings.addWidget(self.spinBox_Roughening)
        self.formLayout_Surroundings.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_Surroundings)
        self.verticalLayout_Simple.addLayout(self.formLayout_Surroundings)
        self.gridLayout_2.addLayout(self.verticalLayout_Simple, 1, 0, 1, 1)
        self.radioButton_Advanced = QtGui.QRadioButton(self.groupBox_Resampling)
        self.radioButton_Advanced.setObjectName(_fromUtf8("radioButton_Advanced"))
        self.gridLayout_2.addWidget(self.radioButton_Advanced, 2, 0, 1, 1)
        self.radioButton_Simple = QtGui.QRadioButton(self.groupBox_Resampling)
        self.radioButton_Simple.setChecked(True)
        self.radioButton_Simple.setObjectName(_fromUtf8("radioButton_Simple"))
        self.gridLayout_2.addWidget(self.radioButton_Simple, 0, 0, 1, 1)
        self.verticalLayout_Advanced = QtGui.QVBoxLayout()
        self.verticalLayout_Advanced.setContentsMargins(10, -1, -1, -1)
        self.verticalLayout_Advanced.setObjectName(_fromUtf8("verticalLayout_Advanced"))
        self.horizontalLayout_Advanced1 = QtGui.QHBoxLayout()
        self.horizontalLayout_Advanced1.setObjectName(_fromUtf8("horizontalLayout_Advanced1"))
        self.label_11 = QtGui.QLabel(self.groupBox_Resampling)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_Advanced1.addWidget(self.label_11)
        self.spinBox_Height = QtGui.QSpinBox(self.groupBox_Resampling)
        self.spinBox_Height.setEnabled(True)
        self.spinBox_Height.setMinimum(1)
        self.spinBox_Height.setMaximum(8)
        self.spinBox_Height.setProperty("value", 5)
        self.spinBox_Height.setObjectName(_fromUtf8("spinBox_Height"))
        self.horizontalLayout_Advanced1.addWidget(self.spinBox_Height)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_Advanced1.addItem(spacerItem1)
        self.label_10 = QtGui.QLabel(self.groupBox_Resampling)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_Advanced1.addWidget(self.label_10)
        self.lineEdit = QtGui.QLineEdit(self.groupBox_Resampling)
        self.lineEdit.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_Advanced1.addWidget(self.lineEdit)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_Advanced1.addItem(spacerItem2)
        self.verticalLayout_Advanced.addLayout(self.horizontalLayout_Advanced1)
        self.horizontalLayout_Advanced2 = QtGui.QHBoxLayout()
        self.horizontalLayout_Advanced2.setObjectName(_fromUtf8("horizontalLayout_Advanced2"))
        self.label_Focus = QtGui.QLabel(self.groupBox_Resampling)
        self.label_Focus.setObjectName(_fromUtf8("label_Focus"))
        self.horizontalLayout_Advanced2.addWidget(self.label_Focus)
        self.toolButton_PointTool = QtGui.QToolButton(self.groupBox_Resampling)
        self.toolButton_PointTool.setObjectName(_fromUtf8("toolButton_PointTool"))
        self.horizontalLayout_Advanced2.addWidget(self.toolButton_PointTool)
        self.verticalLayout_Advanced.addLayout(self.horizontalLayout_Advanced2)
        self.horizontalLayout_Advanced3 = QtGui.QHBoxLayout()
        self.horizontalLayout_Advanced3.setObjectName(_fromUtf8("horizontalLayout_Advanced3"))
        self.label_xmax = QtGui.QLabel(self.groupBox_Resampling)
        self.label_xmax.setObjectName(_fromUtf8("label_xmax"))
        self.horizontalLayout_Advanced3.addWidget(self.label_xmax)
        self.lineEdit_xmax = QtGui.QLineEdit(self.groupBox_Resampling)
        self.lineEdit_xmax.setEnabled(True)
        self.lineEdit_xmax.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_xmax.setReadOnly(True)
        self.lineEdit_xmax.setObjectName(_fromUtf8("lineEdit_xmax"))
        self.horizontalLayout_Advanced3.addWidget(self.lineEdit_xmax)
        self.label_ymax = QtGui.QLabel(self.groupBox_Resampling)
        self.label_ymax.setObjectName(_fromUtf8("label_ymax"))
        self.horizontalLayout_Advanced3.addWidget(self.label_ymax)
        self.lineEdit_ymax = QtGui.QLineEdit(self.groupBox_Resampling)
        self.lineEdit_ymax.setEnabled(True)
        self.lineEdit_ymax.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_ymax.setReadOnly(True)
        self.lineEdit_ymax.setObjectName(_fromUtf8("lineEdit_ymax"))
        self.horizontalLayout_Advanced3.addWidget(self.lineEdit_ymax)
        self.verticalLayout_Advanced.addLayout(self.horizontalLayout_Advanced3)
        self.horizontalLayout_Advanced4 = QtGui.QHBoxLayout()
        self.horizontalLayout_Advanced4.setObjectName(_fromUtf8("horizontalLayout_Advanced4"))
        self.label_xmin = QtGui.QLabel(self.groupBox_Resampling)
        self.label_xmin.setEnabled(True)
        self.label_xmin.setObjectName(_fromUtf8("label_xmin"))
        self.horizontalLayout_Advanced4.addWidget(self.label_xmin)
        self.lineEdit_xmin = QtGui.QLineEdit(self.groupBox_Resampling)
        self.lineEdit_xmin.setEnabled(True)
        self.lineEdit_xmin.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_xmin.setReadOnly(True)
        self.lineEdit_xmin.setObjectName(_fromUtf8("lineEdit_xmin"))
        self.horizontalLayout_Advanced4.addWidget(self.lineEdit_xmin)
        self.label_ymin = QtGui.QLabel(self.groupBox_Resampling)
        self.label_ymin.setObjectName(_fromUtf8("label_ymin"))
        self.horizontalLayout_Advanced4.addWidget(self.label_ymin)
        self.lineEdit_ymin = QtGui.QLineEdit(self.groupBox_Resampling)
        self.lineEdit_ymin.setEnabled(True)
        self.lineEdit_ymin.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_ymin.setReadOnly(True)
        self.lineEdit_ymin.setObjectName(_fromUtf8("lineEdit_ymin"))
        self.horizontalLayout_Advanced4.addWidget(self.lineEdit_ymin)
        self.verticalLayout_Advanced.addLayout(self.horizontalLayout_Advanced4)
        self.gridLayout_2.addLayout(self.verticalLayout_Advanced, 3, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.groupBox_Resampling)
        self.groupBox_DisplayType = QtGui.QGroupBox(DEMPropertiesWidget)
        self.groupBox_DisplayType.setObjectName(_fromUtf8("groupBox_DisplayType"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_DisplayType)
        self.gridLayout_3.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.radioButton_MapCanvas = QtGui.QRadioButton(self.groupBox_DisplayType)
        self.radioButton_MapCanvas.setChecked(True)
        self.radioButton_MapCanvas.setObjectName(_fromUtf8("radioButton_MapCanvas"))
        self.verticalLayout.addWidget(self.radioButton_MapCanvas)
        self.horizontalLayout_ImageFile = QtGui.QHBoxLayout()
        self.horizontalLayout_ImageFile.setObjectName(_fromUtf8("horizontalLayout_ImageFile"))
        self.radioButton_ImageFile = QtGui.QRadioButton(self.groupBox_DisplayType)
        self.radioButton_ImageFile.setEnabled(True)
        self.radioButton_ImageFile.setObjectName(_fromUtf8("radioButton_ImageFile"))
        self.horizontalLayout_ImageFile.addWidget(self.radioButton_ImageFile)
        self.lineEdit_ImageFile = QtGui.QLineEdit(self.groupBox_DisplayType)
        self.lineEdit_ImageFile.setObjectName(_fromUtf8("lineEdit_ImageFile"))
        self.horizontalLayout_ImageFile.addWidget(self.lineEdit_ImageFile)
        self.toolButton_ImageFile = QtGui.QToolButton(self.groupBox_DisplayType)
        self.toolButton_ImageFile.setObjectName(_fromUtf8("toolButton_ImageFile"))
        self.horizontalLayout_ImageFile.addWidget(self.toolButton_ImageFile)
        self.verticalLayout.addLayout(self.horizontalLayout_ImageFile)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.radioButton_SolidColor = QtGui.QRadioButton(self.groupBox_DisplayType)
        self.radioButton_SolidColor.setObjectName(_fromUtf8("radioButton_SolidColor"))
        self.verticalLayout_3.addWidget(self.radioButton_SolidColor)
        self.radioButton_Wireframe = QtGui.QRadioButton(self.groupBox_DisplayType)
        self.radioButton_Wireframe.setEnabled(True)
        self.radioButton_Wireframe.setObjectName(_fromUtf8("radioButton_Wireframe"))
        self.verticalLayout_3.addWidget(self.radioButton_Wireframe)
        self.horizontalLayout_7.addLayout(self.verticalLayout_3)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.label = QtGui.QLabel(self.groupBox_DisplayType)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_7.addWidget(self.label)
        self.lineEdit_Color = QtGui.QLineEdit(self.groupBox_DisplayType)
        self.lineEdit_Color.setObjectName(_fromUtf8("lineEdit_Color"))
        self.horizontalLayout_7.addWidget(self.lineEdit_Color)
        self.toolButton_Color = QtGui.QToolButton(self.groupBox_DisplayType)
        self.toolButton_Color.setObjectName(_fromUtf8("toolButton_Color"))
        self.horizontalLayout_7.addWidget(self.toolButton_Color)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.checkBox_Shading = QtGui.QCheckBox(self.groupBox_DisplayType)
        self.checkBox_Shading.setChecked(False)
        self.checkBox_Shading.setObjectName(_fromUtf8("checkBox_Shading"))
        self.horizontalLayout_10.addWidget(self.checkBox_Shading)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.label_17 = QtGui.QLabel(self.groupBox_DisplayType)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_10.addWidget(self.label_17)
        self.spinBox_demtransp = QtGui.QSpinBox(self.groupBox_DisplayType)
        self.spinBox_demtransp.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_demtransp.sizePolicy().hasHeightForWidth())
        self.spinBox_demtransp.setSizePolicy(sizePolicy)
        self.spinBox_demtransp.setPrefix(_fromUtf8(""))
        self.spinBox_demtransp.setMinimum(0)
        self.spinBox_demtransp.setMaximum(100)
        self.spinBox_demtransp.setSingleStep(10)
        self.spinBox_demtransp.setProperty("value", 0)
        self.spinBox_demtransp.setObjectName(_fromUtf8("spinBox_demtransp"))
        self.horizontalLayout_10.addWidget(self.spinBox_demtransp)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.gridLayout_3.addLayout(self.horizontalLayout_10, 1, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.groupBox_DisplayType)
        self.groupBox_Accessories = QtGui.QGroupBox(DEMPropertiesWidget)
        self.groupBox_Accessories.setObjectName(_fromUtf8("groupBox_Accessories"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_Accessories)
        self.gridLayout_4.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.checkBox_Sides = QtGui.QCheckBox(self.groupBox_Accessories)
        self.checkBox_Sides.setChecked(True)
        self.checkBox_Sides.setObjectName(_fromUtf8("checkBox_Sides"))
        self.horizontalLayout_18.addWidget(self.checkBox_Sides)
        self.label_sidetransp = QtGui.QLabel(self.groupBox_Accessories)
        self.label_sidetransp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_sidetransp.setObjectName(_fromUtf8("label_sidetransp"))
        self.horizontalLayout_18.addWidget(self.label_sidetransp)
        self.spinBox_sidetransp = QtGui.QSpinBox(self.groupBox_Accessories)
        self.spinBox_sidetransp.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_sidetransp.sizePolicy().hasHeightForWidth())
        self.spinBox_sidetransp.setSizePolicy(sizePolicy)
        self.spinBox_sidetransp.setPrefix(_fromUtf8(""))
        self.spinBox_sidetransp.setMinimum(0)
        self.spinBox_sidetransp.setMaximum(100)
        self.spinBox_sidetransp.setSingleStep(10)
        self.spinBox_sidetransp.setProperty("value", 0)
        self.spinBox_sidetransp.setObjectName(_fromUtf8("spinBox_sidetransp"))
        self.horizontalLayout_18.addWidget(self.spinBox_sidetransp)
        self.gridLayout_4.addLayout(self.horizontalLayout_18, 0, 0, 1, 1)
        self.checkBox_Frame = QtGui.QCheckBox(self.groupBox_Accessories)
        self.checkBox_Frame.setObjectName(_fromUtf8("checkBox_Frame"))
        self.gridLayout_4.addWidget(self.checkBox_Frame, 1, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.groupBox_Accessories)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem6)
        self.gridLayout.addLayout(self.verticalLayout_9, 0, 0, 1, 1)

        self.retranslateUi(DEMPropertiesWidget)
        QtCore.QMetaObject.connectSlotsByName(DEMPropertiesWidget)

    def retranslateUi(self, DEMPropertiesWidget):
        DEMPropertiesWidget.setWindowTitle(_translate("DEMPropertiesWidget", "Form", None))
        self.label_DEMLayer.setText(_translate("DEMPropertiesWidget", "DEM Layer", None))
        self.groupBox_Resampling.setTitle(_translate("DEMPropertiesWidget", "Resampling", None))
        self.label_Resolution.setText(_translate("DEMPropertiesWidget", "about 200 x 200 px", None))
        self.label_8.setText(_translate("DEMPropertiesWidget", "X resolution", None))
        self.label_9.setText(_translate("DEMPropertiesWidget", "Y resolution", None))
        self.checkBox_Surroundings.setText(_translate("DEMPropertiesWidget", "Surroundings", None))
        self.label_2.setText(_translate("DEMPropertiesWidget", "Size", None))
        self.label_3.setText(_translate("DEMPropertiesWidget", "Roughening", None))
        self.radioButton_Advanced.setText(_translate("DEMPropertiesWidget", "Advanced (quad tree)", None))
        self.radioButton_Simple.setText(_translate("DEMPropertiesWidget", "Simple", None))
        self.label_11.setText(_translate("DEMPropertiesWidget", "Quad tree height", None))
        self.label_10.setText(_translate("DEMPropertiesWidget", "Quad size", None))
        self.lineEdit.setText(_translate("DEMPropertiesWidget", "64", None))
        self.label_Focus.setText(_translate("DEMPropertiesWidget", "Focus point", None))
        self.toolButton_PointTool.setText(_translate("DEMPropertiesWidget", "Get point from map", None))
        self.label_xmax.setText(_translate("DEMPropertiesWidget", "x", None))
        self.label_ymax.setText(_translate("DEMPropertiesWidget", "y", None))
        self.label_xmin.setText(_translate("DEMPropertiesWidget", "xmin", None))
        self.label_ymin.setText(_translate("DEMPropertiesWidget", "ymin", None))
        self.groupBox_DisplayType.setTitle(_translate("DEMPropertiesWidget", "Display type", None))
        self.radioButton_MapCanvas.setText(_translate("DEMPropertiesWidget", "Map canvas image", None))
        self.radioButton_ImageFile.setText(_translate("DEMPropertiesWidget", "Image file", None))
        self.toolButton_ImageFile.setText(_translate("DEMPropertiesWidget", "Browse...", None))
        self.radioButton_SolidColor.setText(_translate("DEMPropertiesWidget", "Solid color", None))
        self.radioButton_Wireframe.setText(_translate("DEMPropertiesWidget", "Wireframe", None))
        self.label.setText(_translate("DEMPropertiesWidget", "Color", None))
        self.lineEdit_Color.setPlaceholderText(_translate("DEMPropertiesWidget", "0xrrggbb", None))
        self.toolButton_Color.setText(_translate("DEMPropertiesWidget", "...", None))
        self.checkBox_Shading.setText(_translate("DEMPropertiesWidget", "Enable shading", None))
        self.label_17.setText(_translate("DEMPropertiesWidget", "Transparency (%)", None))
        self.groupBox_Accessories.setTitle(_translate("DEMPropertiesWidget", "Sides and frame", None))
        self.checkBox_Sides.setText(_translate("DEMPropertiesWidget", "Build sides", None))
        self.label_sidetransp.setText(_translate("DEMPropertiesWidget", "Transparency (%)", None))
        self.checkBox_Frame.setText(_translate("DEMPropertiesWidget", "Build frame", None))

